### ISSUE TITLE
micropython ESP32 UART to TCP bridge

### ISSUE THREAD

**Issue by jccocco** [tiagocoutinho/us2n#3]
Good Night Mr. Tiago
I'm writing from Caracas Venezuela
I'm a software programmer in Visual Basic 6 and Visual Estudio
Recently I began to program in Micropython and the ESP8266 / ESP32
I saw your work in GitHub about the ESP32 UART to TCP bridge. Good job,
as I'm newbie programing in micropython, however I understood 85% of your code.
Well I tried to use your project but it does not run, I got three Errors:
Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "us2n.py", line 236, in server
  File "us2n.py", line 19, in read_config
ValueError: syntax error in JSON
Can you help me Mr. Tiago?

P.D.: this is the json file I used in ESP32
import json

config = {
    "name": "SuperESP32",
    "verbose": False,
    "wlan": {
        "sta": {
            "essid": "vanessa",
            "password": "jc211292",
        },
    },
    "bridges": [
        {
            "tcp": {
                "bind": ["", 8000],
            },
            "uart": {
                "port": 1,
                "baudrate": 9600,
                "bits": 8,
                "parity": None,
                "stop": 1,
            },
        },
    ],
}

with open('us2n.json', 'w') as f:
    json.dump(config, f)

**Comment by tiagocoutinho** [comment]
Hope it's not too late.
From what I understand you copied the entire python example I show in the README to a `us2n.json` file.

Please only put in `us2n.json` the json content like this:

```json
{
	"name": "SuperESP32",
	"verbose": false,
	"wlan": {
		"sta": {
			"essid": "<name of your access point>",
			"password": "<password of your access point>"
		}
	},
	"bridges": [{
		"tcp": {
			"bind": ["", 8000]
		},
		"uart": {
			"port": 1,
			"baudrate": 9600,
			"bits": 8,
			"parity": null,
			"stop": 1
		}
	}]
}
```

(hint: you can use a JSON validator like https://jsonlint.com/ to make sure you have valid JSON content in the file)

The README is not well explained. I will correct it so more people don't fall into the same trap.
